### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by felicitus** [zendmaniacs/extjs5#1]
After pulling in this package via composer, I end up with having a directory called "extras/library/extjs5". How am I able to put this into my web root?

**Comment by epoleacov** [comment]
Hi. Just use it inside of composer.json like extra package:
```
"require" : {
        "zendmaniacs/extjs5": "dev-master"
    },
 "extra": {
        "installer-paths": {
            "public/js/packages/{$name}": ["zendmaniacs/extjs5"]
        }
    },
```
"public/js/packages/" is path where you want to put it in your project.
Have a nice day.
Evgheni.

**Comment by felicitus** [comment]
Thank you! I will try that tomorrow and send a pull request to include that into the documentation if it works for me.

**Comment by felicitus** [comment]
Works nice.
